const PUBLIC_PROFILE_FIELDS = [
  "name",
  "gender",
  "age",
  "location",
  "tripLocation.name",
  "tripLocation.city",
  "tripLocation.state",
  "tripLocation.country",
  "tripLocation.countryCode",
  "bio",
  "interests",
  "preferredDestinations",
  "travelStyle",
  "budget",
  "tripDates",
  "tripDuration",
  "questionnaire.accommodationPreference",
  "questionnaire.companionScope",
  "questionnaire.companionPriority",
  "questionnaire.dealBreaker",
  "photo",
  "photoURL",
  "photos",
].join(" ");

module.exports = PUBLIC_PROFILE_FIELDS;
